"""empty message

Revision ID: 024db06f5d7b
Revises: a6c5d47780c3
Create Date: 2021-04-16 01:19:21.368684

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '024db06f5d7b'
down_revision = 'a6c5d47780c3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('favorites', sa.Column('entityType', sa.String(length=250), nullable=False))
    op.add_column('favorites', sa.Column('favoriteName', sa.String(length=250), nullable=False))
    op.add_column('favorites', sa.Column('isFav', sa.Boolean(), nullable=False))
    op.drop_constraint('favorites_ibfk_1', 'favorites', type_='foreignkey')
    op.drop_constraint('favorites_ibfk_2', 'favorites', type_='foreignkey')
    op.drop_column('favorites', 'created')
    op.drop_column('favorites', 'characters_id')
    op.drop_column('favorites', 'planets_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('favorites', sa.Column('planets_id', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('favorites', sa.Column('characters_id', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('favorites', sa.Column('created', mysql.DATETIME(), nullable=False))
    op.create_foreign_key('favorites_ibfk_2', 'favorites', 'planets', ['planets_id'], ['id'])
    op.create_foreign_key('favorites_ibfk_1', 'favorites', 'characters', ['characters_id'], ['id'])
    op.drop_column('favorites', 'isFav')
    op.drop_column('favorites', 'favoriteName')
    op.drop_column('favorites', 'entityType')
    # ### end Alembic commands ###
