"""empty message

Revision ID: 0f8ed393f532
Revises: 7223ec5da000
Create Date: 2021-04-16 00:45:18.379761

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0f8ed393f532'
down_revision = '7223ec5da000'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('favorites', sa.Column('testedBy', sa.String(length=250), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('favorites', 'testedBy')
    # ### end Alembic commands ###
