"""empty message

Revision ID: 5cbea2648b5f
Revises: 771a6bb010b8
Create Date: 2021-04-18 02:30:06.399571

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5cbea2648b5f'
down_revision = '771a6bb010b8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('favorites', sa.Column('favoriteID', sa.String(length=250), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('favorites', 'favoriteID')
    # ### end Alembic commands ###
