"""empty message

Revision ID: 771a6bb010b8
Revises: 9135f41486f0
Create Date: 2021-04-18 02:29:43.317108

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '771a6bb010b8'
down_revision = '9135f41486f0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('favorites', 'favoriteID')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('favorites', sa.Column('favoriteID', mysql.INTEGER(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
