"""empty message

Revision ID: 9135f41486f0
Revises: e36bbf8df902
Create Date: 2021-04-18 01:51:09.336321

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9135f41486f0'
down_revision = 'e36bbf8df902'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('favorites', sa.Column('favoriteID', sa.Integer(), nullable=False))
    op.drop_constraint('favorites_ibfk_3', 'favorites', type_='foreignkey')
    op.drop_column('favorites', 'user_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('favorites', sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('favorites_ibfk_3', 'favorites', 'user', ['user_id'], ['id'])
    op.drop_column('favorites', 'favoriteID')
    # ### end Alembic commands ###
