"""empty message

Revision ID: b9bfa60a958e
Revises: 0f8ed393f532
Create Date: 2021-04-16 00:46:06.475382

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b9bfa60a958e'
down_revision = '0f8ed393f532'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('favorites', 'testedBy')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('favorites', sa.Column('testedBy', mysql.VARCHAR(length=250), nullable=False))
    # ### end Alembic commands ###
