"""empty message

Revision ID: e36bbf8df902
Revises: 024db06f5d7b
Create Date: 2021-04-18 01:45:23.016399

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e36bbf8df902'
down_revision = '024db06f5d7b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('favorites', 'editedBy')
    op.drop_column('favorites', 'createdBy')
    op.drop_column('favorites', 'edited')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('favorites', sa.Column('edited', mysql.DATETIME(), nullable=False))
    op.add_column('favorites', sa.Column('createdBy', mysql.VARCHAR(length=250), nullable=False))
    op.add_column('favorites', sa.Column('editedBy', mysql.VARCHAR(length=250), nullable=False))
    # ### end Alembic commands ###
